name: Dependency Check

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 500
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
      
    - name: Build with dotnet
      run: dotnet build --configuration Release

    # SUCCESS
    - name: Dependency Check Scan
